import logging
import os
import requests
from requests.auth import HTTPBasicAuth

logger = logging.getLogger(__name__)

JIRA_URL         = os.getenv("JIRA_URL", "")
JIRA_EMAIL       = os.getenv("JIRA_EMAIL", "")
JIRA_API_TOKEN   = os.getenv("JIRA_API_TOKEN", "")
JIRA_PROJECT_KEY = os.getenv("JIRA_PROJECT_KEY", "KAN")

# Skip session logout related rule IDs and groups
_SKIP_GROUPS = {"session_logout", "authentication_success", "pam"}
_SKIP_RULES  = {"5501", "5502", "5715"}

_PRIORITY_MAP = {
    "CRITICAL": "Highest",
    "HIGH":     "High",
    "MEDIUM":   "Medium",
    "LOW":      "Low",
    "INFO":     None,  # never create ticket for INFO
}


def _should_create_ticket(report):
    risk = report["risk"]["overall"]
    if risk == "INFO":
        return False
    # Skip session logout alerts
    groups = report["alert"].get("groups", [])
    rule_id = str(report["alert"].get("rule_id", ""))
    for g in groups:
        if g.lower() in _SKIP_GROUPS:
            return False
    if rule_id in _SKIP_RULES:
        return False
    return True


def _build_description(report, slack_permalink):
    a     = report["alert"]
    risk  = report["risk"]
    wazuh = report.get("wazuh_link", "")

    lines = []
    lines.append(f"*Risk Level:* {risk['overall']}")
    lines.append(f"*Timestamp:* {a['timestamp']}")
    lines.append(f"*Recommended Action:* {risk.get('recommended_action', 'N/A')}")
    lines.append("")
    lines.append("----")
    lines.append("*INVESTIGATION LINKS*")
    if wazuh:
        lines.append(f"Wazuh Dashboard: {wazuh}")
    if slack_permalink:
        lines.append(f"Slack Alert (full details): {slack_permalink}")
    lines.append("")
    lines.append("----")
    lines.append(f"Generated by Wazuh Enrichment Pipeline | Alert ID: {a['id']}")
    return "\n".join(lines)


def create_ticket(report, slack_permalink=""):
    if not JIRA_URL or not JIRA_EMAIL or not JIRA_API_TOKEN:
        logger.warning("Jira not configured - skipping")
        return None

    if not _should_create_ticket(report):
        logger.info("Jira ticket skipped — risk=INFO or session logout alert")
        return None

    risk     = report["risk"]["overall"]
    priority = _PRIORITY_MAP.get(risk, "Medium")
    a        = report["alert"]
    h        = report["host"]

    summary = f"[{risk}] {a['rule_name']} — {h['name']} (Rule ID: {a['rule_id']})"
    description = _build_description(report, slack_permalink)

    payload = {
        "fields": {
            "project":     {"key": JIRA_PROJECT_KEY},
            "summary":     summary,
            "description": description,
            "issuetype":   {"name": "Task"},
            "priority":    {"name": priority},
        }
    }

    try:
        resp = requests.get(
            f"{JIRA_URL}/rest/api/2/issue",
            json=payload,
            auth=HTTPBasicAuth(JIRA_EMAIL, JIRA_API_TOKEN),
            headers={"Accept": "application/json", "Content-Type": "application/json"},
            timeout=15,
        )
        resp.raise_for_status()
        data       = resp.json()
        ticket_key = data.get("key", "")
        ticket_url = f"{JIRA_URL}/browse/{ticket_key}"
        logger.info("Jira ticket created: %s — %s", ticket_key, ticket_url)
        return {"key": ticket_key, "url": ticket_url}
    except Exception as exc:
        logger.error("Jira error: %s", exc)
        return None


# ── Jira Status Poller ────────────────────────────────────────────────────────

import threading
from metrics import set_gauge

def _poll_jira_status():
    """Poll Jira every 60s and update Prometheus gauges for ticket counts."""
    import time
    while True:
        try:
            resp = requests.get(
                f"{JIRA_URL}/rest/api/3/search/jql",
                auth=HTTPBasicAuth(JIRA_EMAIL, JIRA_API_TOKEN),
                headers={"Accept": "application/json", "Content-Type": "application/json"},
                params={
                    "jql": f"project={JIRA_PROJECT_KEY}",
                    "fields": "status",
                    "maxResults": 1000,
                },
                timeout=15,
            )
            resp.raise_for_status()
            issues = resp.json().get("issues", [])

            counts = {"To Do": 0, "In Progress": 0, "Done": 0}
            for issue in issues:
                status = issue.get("fields", {}).get("status", {}).get("name", "")
                if status in counts:
                    counts[status] += 1

            set_gauge("jira_tickets_total", counts["To Do"] + counts["In Progress"] + counts["Done"])
            set_gauge("jira_tickets_todo",        counts["To Do"])
            set_gauge("jira_tickets_in_progress",  counts["In Progress"])
            set_gauge("jira_tickets_resolved",     counts["Done"])

            logger.info(
                "Jira poll: todo=%d in_progress=%d done=%d",
                counts["To Do"], counts["In Progress"], counts["Done"]
            )
        except Exception as exc:
            logger.warning("Jira poll error: %s", exc)

        time.sleep(60)


def start_jira_poller():
    """Start the Jira status poller in a background thread."""
    if not JIRA_URL or not JIRA_EMAIL or not JIRA_API_TOKEN:
        logger.warning("Jira not configured — poller not started")
        return
    thread = threading.Thread(target=_poll_jira_status, daemon=True)
    thread.start()
    logger.info("Jira status poller started (60s interval)")
